#!/usr/bin/env node
/**
 * link_cases_to_theory.js
 *
 * Reads all case files, extracts theory_tags, scans Theory vault notes for
 * matching tags, and appends an "## Empirical Basis" section to each theory
 * note listing cases that instantiate that mechanism.
 *
 * Run during night wake or on-demand.
 * Safe to re-run: skips notes where "## Empirical Basis" already exists,
 * or updates the section if called with --update flag.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, '../..');
const CASES_DIR = path.join(PROJECT_ROOT, 'workspace/cases');
const THEORY_DIR = path.join(PROJECT_ROOT, 'obsidian/ComradeClaw/Theory');

const UPDATE_MODE = process.argv.includes('--update');
const DRY_RUN = process.argv.includes('--dry-run');

// Tags that are internal-only and shouldn't be used for cross-linking
const SKIP_TAGS = new Set(['theory', 'epistemology', 'method', 'foundation',
  'trotsky', 'mao', 'goldman', 'mayday2026', 'labor', 'organizing', 'leverage']);

function loadCases() {
  const caseFiles = fs.readdirSync(CASES_DIR)
    .filter(f => f.endsWith('.json') && f !== 'README.md');

  const cases = [];
  for (const file of caseFiles) {
    try {
      const raw = fs.readFileSync(path.join(CASES_DIR, file), 'utf8');
      const data = JSON.parse(raw);
      if (data.theory_tags && data.theory_tags.length > 0) {
        cases.push({ ...data, _file: file });
      }
    } catch (e) {
      console.warn(`  ⚠️  Could not load case ${file}: ${e.message}`);
    }
  }
  return cases;
}

function parseFrontmatterTags(content) {
  const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
  if (!frontmatterMatch) return [];

  const frontmatter = frontmatterMatch[1];
  const tagsMatch = frontmatter.match(/^tags:\s*\[([^\]]+)\]/m);
  if (!tagsMatch) return [];

  return tagsMatch[1].split(',').map(t => t.trim().toLowerCase());
}

function findMatchingCases(noteTagsRaw, allCases) {
  // Normalize note tags: remove internal-only tags, lowercase
  const noteTags = new Set(
    noteTagsRaw
      .map(t => t.toLowerCase().trim())
      .filter(t => !SKIP_TAGS.has(t))
  );

  if (noteTags.size === 0) return [];

  const matches = [];
  for (const c of allCases) {
    const caseTags = c.theory_tags.map(t => t.toLowerCase().trim());
    const shared = caseTags.filter(t => noteTags.has(t));
    if (shared.length >= 1) {
      matches.push({ ...c, _sharedTags: shared });
    }
  }

  // Sort by number of shared tags descending, then by name
  matches.sort((a, b) => {
    if (b._sharedTags.length !== a._sharedTags.length) {
      return b._sharedTags.length - a._sharedTags.length;
    }
    return a.name.localeCompare(b.name);
  });

  return matches;
}

function buildEmpiricalBasisSection(matches, noteFile) {
  const today = new Date().toISOString().slice(0, 10);

  let section = `\n---\n\n## Empirical Basis\n\n`;
  section += `*Auto-generated by link_cases_to_theory.js — cases whose theory_tags overlap with this note's framework. Last updated: ${today}.*\n\n`;

  for (const c of matches) {
    const relPath = path.relative(
      path.dirname(path.join(PROJECT_ROOT, 'obsidian/ComradeClaw/Theory', noteFile)),
      path.join(PROJECT_ROOT, 'workspace/cases', c._file)
    ).replace(/\\/g, '/');

    const statusIcon = c.active ? '🟢' : '⚫';
    const sharedTagsStr = c._sharedTags.join(', ');

    section += `### ${statusIcon} [${c.name}](${relPath})\n`;
    section += `*${c.date_range} — ${c.location} — \`${c.form}\`*\n\n`;
    section += `**Shared mechanisms:** \`${sharedTagsStr}\`\n\n`;

    // One-line description from notes field, or fall back to outcome excerpt
    const description = c.notes
      ? c.notes.split('.')[0] + '.'
      : c.outcome.split('.')[0] + '.';
    section += `> ${description}\n\n`;
  }

  return section.trimEnd() + '\n';
}

function processTheoryNote(noteFile, allCases) {
  const notePath = path.join(THEORY_DIR, noteFile);
  const content = fs.readFileSync(notePath, 'utf8');

  const hasExistingSection = content.includes('## Empirical Basis');

  if (hasExistingSection && !UPDATE_MODE) {
    console.log(`  ⏭️  ${noteFile} — Empirical Basis exists, skipping (use --update to refresh)`);
    return { status: 'skipped', reason: 'section_exists' };
  }

  const noteTags = parseFrontmatterTags(content);
  const matches = findMatchingCases(noteTags, allCases);

  if (matches.length === 0) {
    console.log(`  ○  ${noteFile} — no matching cases (tags: ${noteTags.filter(t => !SKIP_TAGS.has(t)).join(', ') || 'none usable'})`);
    return { status: 'no_matches', note: noteFile };
  }

  const newSection = buildEmpiricalBasisSection(matches, noteFile);

  let newContent;
  if (hasExistingSection && UPDATE_MODE) {
    // Replace existing section
    newContent = content.replace(
      /\n---\n\n## Empirical Basis[\s\S]*?(?=\n---\n\n##|\n## (?!Empirical)|\n---\n*$|$)/,
      newSection
    );
    if (newContent === content) {
      // Fallback: append/replace from header to end
      const sectionStart = content.indexOf('\n## Empirical Basis');
      if (sectionStart !== -1) {
        newContent = content.slice(0, sectionStart) + newSection;
      } else {
        newContent = content + newSection;
      }
    }
  } else {
    // Append before "## Relationship to Other Theory Notes" or "## Status" if present
    const insertBefore = ['## Relationship to Other Theory Notes', '## Status'];
    let inserted = false;

    for (const marker of insertBefore) {
      const idx = content.indexOf('\n' + marker);
      if (idx !== -1) {
        newContent = content.slice(0, idx) + '\n' + newSection + content.slice(idx + 1);
        inserted = true;
        break;
      }
    }

    if (!inserted) {
      newContent = content.trimEnd() + '\n\n' + newSection;
    }
  }

  if (DRY_RUN) {
    console.log(`  [DRY RUN] Would write ${noteFile} with ${matches.length} cases`);
    console.log(newSection);
    return { status: 'dry_run', note: noteFile, caseCount: matches.length };
  }

  fs.writeFileSync(notePath, newContent, 'utf8');
  console.log(`  ✅ ${noteFile} — appended ${matches.length} case(s): ${matches.map(c => c.id).join(', ')}`);

  return {
    status: hasExistingSection ? 'updated' : 'appended',
    note: noteFile,
    cases: matches.map(c => c.id),
    sharedTags: matches.map(c => ({ id: c.id, tags: c._sharedTags }))
  };
}

function main() {
  console.log('link_cases_to_theory.js');
  console.log(`Mode: ${UPDATE_MODE ? 'update' : 'append-new-only'}${DRY_RUN ? ' (dry run)' : ''}`);
  console.log('');

  // Load all cases
  const allCases = loadCases();
  console.log(`Loaded ${allCases.length} cases with theory_tags`);

  // List tag coverage
  const tagFreq = {};
  for (const c of allCases) {
    for (const t of c.theory_tags) {
      tagFreq[t] = (tagFreq[t] || 0) + 1;
    }
  }
  console.log(`Top tags: ${Object.entries(tagFreq).sort((a,b) => b[1]-a[1]).slice(0,8).map(([t,n]) => `${t}(${n})`).join(', ')}`);
  console.log('');

  // Process each theory note
  const noteFiles = fs.readdirSync(THEORY_DIR)
    .filter(f => f.endsWith('.md'));

  console.log(`Processing ${noteFiles.length} theory notes:\n`);

  const results = [];
  for (const noteFile of noteFiles) {
    const result = processTheoryNote(noteFile, allCases);
    results.push(result);
  }

  // Summary
  console.log('\n--- Summary ---');
  const appended = results.filter(r => r.status === 'appended').length;
  const updated = results.filter(r => r.status === 'updated').length;
  const skipped = results.filter(r => r.status === 'skipped').length;
  const noMatch = results.filter(r => r.status === 'no_matches').length;

  console.log(`Appended: ${appended} | Updated: ${updated} | Skipped: ${skipped} | No matches: ${noMatch}`);

  if (appended + updated > 0) {
    console.log('\nTheory notes updated:');
    for (const r of results.filter(r => r.status === 'appended' || r.status === 'updated')) {
      console.log(`  ${r.note}: ${r.cases.join(', ')}`);
    }
  }
}

main();
